/*
 * Copyright 2016-2025 NXP
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 *
 */

#include "board.h"
#include "peripherals.h"
#include "pin_mux.h"
#include "clock_config.h"
#include "fsl_debug_console.h"

#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"
#include "semphr.h"

#include "app_types.h"
#include "led.h"
#include "adc.h"
#include "max7219.h"
#include "tasks.h"

/* ------------------------------------------------------------------ */
/* Shared FreeRTOS objects (declared extern in app_types.h)            */
/* ------------------------------------------------------------------ */
QueueHandle_t     g_sensorQueue  = NULL;
extern SemaphoreHandle_t g_buttonSema;
SemaphoreHandle_t g_statusMutex  = NULL;

/* ------------------------------------------------------------------ */
/* Shared application state (declared extern in app_types.h)           */
/* ------------------------------------------------------------------ */
bool         g_systemStarted = false;
bool         g_alertLatched  = false;
SensorPacket g_latestPacket  = { 0 };

/* ------------------------------------------------------------------ */
/* main                                                                 */
/* ------------------------------------------------------------------ */
int main(void) {
    /* Board init (generated by MCUXpresso Config Tools) */
    BOARD_InitBootPins();
    BOARD_InitBootClocks();
    BOARD_InitBootPeripherals();

#ifndef BOARD_INIT_DEBUG_CONSOLE_PERIPHERAL
    BOARD_InitDebugConsole();
#endif

    /* Peripheral drivers */
    LED_Init();
    LED_OffAll();
    ADC_Init();
    MAX7219_Init();

    /* FreeRTOS objects */
    g_sensorQueue = xQueueCreate(1, sizeof(SensorPacket));
    g_buttonSema  = xSemaphoreCreateBinary();
    g_statusMutex = xSemaphoreCreateMutex();

    if ((g_sensorQueue == NULL) || (g_buttonSema == NULL) || (g_statusMutex == NULL)) {
        PRINTF("ERROR: RTOS object creation failed\r\n");
        while (1) { __asm volatile ("nop"); }
    }

    /* Tasks
     *  Priority 3 (highest) : buttonTask  — latency sensitive
     *  Priority 2            : sensorTask, alertTask
     *  Priority 1 (lowest)   : printTask
     */
    xTaskCreate(sensorTask, "sensor", configMINIMAL_STACK_SIZE + 250, NULL, 2, NULL);
    xTaskCreate(buttonTask, "button", configMINIMAL_STACK_SIZE + 200, NULL, 3, NULL);
    xTaskCreate(alertTask,  "alert",  configMINIMAL_STACK_SIZE + 200, NULL, 2, NULL);
    xTaskCreate(printTask,  "print",  configMINIMAL_STACK_SIZE + 350, NULL, 1, NULL);

    vTaskStartScheduler();


    while (1) { __asm volatile ("nop"); }
    return 0;
}

/* ------------------------------------------------------------------ */
/* FreeRTOS hooks                                                       */
/* ------------------------------------------------------------------ */
void vApplicationMallocFailedHook(void) {
    taskDISABLE_INTERRUPTS();
    LED_SetRGB(true, false, false);   /* RED = fatal */
    while (1) { __asm volatile ("nop"); }
}

void vApplicationStackOverflowHook(TaskHandle_t pxTask, char *pcTaskName) {
    (void)pxTask;
    (void)pcTaskName;
    taskDISABLE_INTERRUPTS();
    LED_SetRGB(true, false, false);   /* RED = fatal */
    while (1) { __asm volatile ("nop"); }
}
